# Generated by Django 3.2.5 on 2022-02-23 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Post')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('domaine', models.CharField(blank=True, choices=[('GEOMATIQUE', 'GEOMATIQUE'), ('BTP', 'BTP'), ('ARTISANAT', 'ARTISANAT')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('domicile', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone1', models.CharField(blank=True, max_length=8, null=True)),
                ('phone2', models.CharField(blank=True, max_length=8, null=True)),
                ('phone_fix', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
