# Generated by Django 3.1.5 on 2021-05-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('PERSONNE', 'Personne'), ('SOCIETE', 'Societe')], max_length=30, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('HOMME', 'Homme'), ('FEMME', 'Femme')], max_length=10, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOM')),
                ('prenom', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRENOM')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, verbose_name='N°MATRICULE')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/identite', verbose_name='PHOTO IDENTITE')),
                ('contact', models.CharField(blank=True, max_length=8, null=True, verbose_name='TELEPHONE')),
                ('n_cin', models.CharField(blank=True, max_length=50, null=True, verbose_name='CIN')),
                ('nina', models.CharField(blank=True, max_length=50, null=True, verbose_name='NINA')),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='PROFESSION')),
                ('rcimm', models.CharField(blank=True, max_length=50, null=True, verbose_name='REGISTRE DE COMMERCE')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('siege_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='SIEGE SOCIAL')),
                ('responsable', models.CharField(blank=True, max_length=50, null=True, verbose_name='RESPONSABLE')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ADRESSE EMAIL')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
