# Generated by Django 3.2.5 on 2022-02-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotisation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='person_mesure',
        ),
        migrations.RemoveField(
            model_name='order',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentOrder',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='cotisation',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Mesure',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
