# Generated by Django 3.2.5 on 2022-01-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_1', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('domicile', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('contact_2', models.CharField(blank=True, max_length=8, null=True)),
                ('phone_fix', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posted', verbose_name='Photo_commande')),
                ('post', models.TextField(blank=True, max_length=2000, verbose_name=' post')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='title')),
                ('code_post', models.CharField(blank=True, max_length=30, verbose_name='Code post')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cercle',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='id_cercle',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='person_mesure',
        ),
        migrations.RemoveField(
            model_name='order',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentOrder',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='village',
            name='id_commune',
        ),
        migrations.DeleteModel(
            name='Cercle',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Mesure',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
