# Generated by Django 3.2.5 on 2022-01-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20220106_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='contact_2',
            new_name='phone2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='code_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='address',
            name='phone1',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='contacts.address', verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name_dom',
            field=models.CharField(blank=True, choices=[('GEOMATIQUE', 'GEOMATIQUE'), ('BTP', 'BTP'), ('ARTISANAT', 'ARTISANAT')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='domicile',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, max_length=5000, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
    ]
