# Generated by Django 3.2.5 on 2022-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20220109_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, max_length=10000, verbose_name='post'),
        ),
    ]
