# Generated by Django 3.1.5 on 2021-05-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('status', models.CharField(choices=[('Client', 'CLIENT'), ('Ouvrier', 'OUVRIER'), ('Apprenti', 'APPRENTI'), ('Fournisseur', 'FOURNISSEUR'), ('Company', 'COMPANY')], default='CLIENT', max_length=20)),
                ('sex', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autres')], default='Homme', max_length=20)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(choices=[('G', 'Grande'), ('M', 'Moyenne'), ('P', 'Petite')], default='Grande', max_length=20)),
                ('domicile', models.CharField(blank=True, default='Lafiabougou', max_length=30, null=True)),
                ('create_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(choices=[('Boubou', 'Boubou'), ('Grand Boubou', 'Grand Boubou'), ('Chemise Complet', 'Chemise Complet'), ('Chemise Manche Long', 'Chemise Manche Long'), ('Chemise Manche Court', 'Chemise Manche Court'), ('Pagne Jupe', 'Pagne Jupe'), ('Pagne Complet', 'Pagne Complet'), ('Pagne Maniere', 'Pagne Maniere'), ('Patanlon', 'Patanlon'), ('Tenu Scolaire', 'Tenu Scolaire'), ('Tenu Securite', 'Tenu Securite'), ('AUTRES', 'AUTRES')], default='', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/profil%Y/%m/%d', verbose_name='img_command')),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coude', models.FloatField(blank=True, null=True)),
                ('epaule', models.FloatField(blank=True, null=True)),
                ('manche', models.FloatField(blank=True, null=True)),
                ('tour_manche', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('poitrine', models.FloatField(blank=True, null=True)),
                ('longueur_boubou', models.FloatField(blank=True, null=True)),
                ('longueur_patanlon', models.FloatField(blank=True, null=True)),
                ('fesse', models.FloatField(blank=True, null=True)),
                ('ceinture', models.FloatField(blank=True, null=True)),
                ('cuisse', models.FloatField(blank=True, null=True)),
                ('patte', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('mesure_client', models.ManyToManyField(to='kalaliso.Produit', verbose_name='Mesure Par Produit')),
                ('person_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.person', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rendez_vous', models.DateTimeField()),
                ('livre', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('command_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalaliso.person', verbose_name='Titulaire command')),
                ('products', models.ManyToManyField(to='kalaliso.Produit', verbose_name='list_commande')),
            ],
        ),
    ]
